### PR TITLE
fix tests when docker with consul are used

### PR DESCRIPTION
**Pull request by aatarasoff**
My consul host in docker container is 0227387ce42f and tests fails.

### CODE REVIEW

**Comment by spencergibb** [comment]
Have you signed the [contributor's agreement](https://support.springsource.com/spring_committer_signup)?

**Comment by aatarasoff** [comment]
Yep, just now.

**Comment by spencergibb** [comment]
awesome, thanks!

**Comment by spencergibb** [comment]
Closed via b4154125d25981b17c70923a86c8622fec8018dd

**Pull request closed without merging**
