### PR TITLE
add acl-token to ttl

### LINKED ISSUE #559: Ttl Heartbeats don't send acl token if configured
If heartbeat is enabled paired with acl tokens, then the heartbeat task does not configure the token to use when communicating with the consul server

```yml
spring.cloud.consul.discovery:
  acl-token: ${uuid}
  heartbeat.enabled: true
```

ConsulHeartbeatTask has this method call to agentCheckPass:

```java
@Override
public void run() {
	TtlScheduler.this.client.agentCheckPass(this.checkId);
	if (log.isDebugEnabled()) {
		log.debug("Sending consul heartbeat for: " + this.checkId);
	}
}
```

Which without a token, you'll see the following stack trace:

```
com.ecwid.consul.v1.OperationException: OperationException(statusCode=403, statusMessage='Forbidden', statusContent='Permission denied')
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:211) ~[consul-api-1.4.1.jar:na]
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:198) ~[consul-api-1.4.1.jar:na]
        at com.ecwid.consul.v1.agent.AgentConsulClient.agentCheckPass(AgentConsulClient.java:193) ~[consul-api-1.4.1.jar:na]
        at com.ecwid.consul.v1.ConsulClient.agentCheckPass(ConsulClient.java:259) ~[consul-api-1.4.1.jar:na]
        at org.springframework.cloud.consul.discovery.TtlScheduler$ConsulHeartbeatTask.run(TtlScheduler.java:95) ~[spring-cloud-consul-discovery-2.1.1.RELEASE.jar:2.1.1.RELEASE]
```

Which can be overridden to pass a token too (can be null too):

```java
@Override
public void run() {
	TtlScheduler.this.client.agentCheckPass(this.checkId, this.aclToken);
	if (log.isDebugEnabled()) {
		log.debug("Sending consul heartbeat for: " + this.checkId);
	}
}
```

So any reason why i can't submit a simple PR to fix this (Ie am i missing something?)

### PR DESCRIPTION
**Pull request by varnson**
resubmit for #571 to fix #559 .
@spencergibb I'm sorry for a new PR.

### CODE REVIEW

**Comment by kevinimbrechts** [comment]
Hello
What about this PR ? I always have a 403 :
`http: Request PUT /v1/agent/check/pass/service:casconfigserver-8888, error: Permission denied`
Thanks.

**Comment by varnson** [comment]
There are ci errors, and I think the sleep is too short in the remove test. But I do not know how to trigger the ci again.

**Comment by spencergibb** [comment]
Not sure what to do, tests continue to fail.

**Comment by varnson** [comment]
@spencergibb The ci error is "This job has been blocked because resource-class:large is not available on your plan. Please upgrade to continue building.", not compile error or test error.

**Comment by spencergibb** [comment]
You have to 
```
$ git rebase -i master
$ git push --force
```
to pick up this change https://github.com/spring-cloud/spring-cloud-consul/commit/5118afce4f96d9e9bba63f03cc73452877300ae4

**Comment by chenzhiguo** [comment]
This old issue, how is it still not repaired? Do you need to wait? @spencergibb 
What can I help?

**Comment by chenzhiguo** [comment]
I think this is a very serious bug, should not be dragged for so long.

**Comment by chenjinkai** [comment]
这个bug需要赶紧修复了。大哥们。

**Comment by TimurDaas** [comment]
Hello guys, do you plan to fix this bug?

**Comment by jefflaifu** [comment]
3 years, this problem is still.... i wonder why

**Comment by lmove** [comment]
Hi! As you probably know, this PR introduces some breaking changes. Our academic tool, [BreakBot](https://github.com/alien-tools/breakbot), helps developers better assess the impact of these changes on client projects. BreakBot checked the top 100 most starred clients of spring-cloud-consul on GitHub and found out that only one is impacted by one of the breaking changes.

You can find the full BreakBot report in our fork repository [breakbot-playground/spring-cloud-consul](https://github.com/breakbot-playground/spring-cloud-consul/pull/1/checks).

We hope this information about the impact of this PR's changes is valuable to you, and apologize otherwise. If you're willing to help, we would kindly ask for your help to fill in a [5-minutes survey](https://survey.breakbot.net/index.php/418865/newtest/Y?ID=spring-cloud-spring-cloud-consul-590) about the report. Your feedback will help us improve the tool and help us in our research!

**Comment by mmm8955405** [comment]
> 3 years, this problem is still.... i wonder why

There is no reason, because technology is really rubbish! Four years of bugs, think about it

**Comment by spencergibb** [comment]
This was fixed in 226e08a8eb4cb77ee36861195a234020ee12d665

**Comment by mmm8955405** [comment]
> [这已在226e08a](https://github.com/spring-cloud/spring-cloud-consul/commit/226e08a8eb4cb77ee36861195a234020ee12d665)中修改[](https://github.com/spring-cloud/spring-cloud-consul/commit/226e08a8eb4cb77ee36861195a234020ee12d665)

Is there any release version available? If you submit code and then close the bug, have you tried testing or released an available version. Version 4.0.1 still fails

**Comment by mmm8955405** [comment]
> [这已在226e08a](https://github.com/spring-cloud/spring-cloud-consul/commit/226e08a8eb4cb77ee36861195a234020ee12d665)中修改[](https://github.com/spring-cloud/spring-cloud-consul/commit/226e08a8eb4cb77ee36861195a234020ee12d665)

Can you teach me how to introduce the main branch from maven? The main branch reference

**Comment by spencergibb** [comment]
Main will be released in two weeks. See https://github.com/spring-cloud/spring-cloud-release/milestones?direction=asc&sort=due_date&state=open

**Pull request closed without merging**
