### PR TITLE
Uses ACL token when get servers.

### PR DESCRIPTION
**Pull request by bomee**
Uses ACL token when get servers.

fixes gh-293

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bomee Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=294)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=294) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bomee Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=294)!

**Comment by bomee** [comment]
The feature depend on consul server and an acl_rule, i pass the code in my environment

**Comment by spencergibb** [comment]
We have existing tests that use ACLs see https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClientAclTests.java and https://github.com/spring-cloud/spring-cloud-consul/tree/master/src/test/resources/consul_acl

**Comment by bomee** [comment]
Thanks.I refer to the existing test to complete the test.

**Pull request merged**
