### PR TITLE
Support different format for defaultContext

### PR DESCRIPTION
**Pull request by tommyk-gears**
Allow the format for the defaultContext to be configured via
ConsulConfigProperties#defaultContextFormat.

Since this can create a mixture of formats among the contexts
loaded from ConsulPropertySourceLocator we need to keep track
of the format for each context when adding suffixes, and resolving
profile separator, and when loading the actual data from consul.
Because of this the ConsulPropertySourceLocator has been slightly
refactored.

Fixes gh-637

### CODE REVIEW

**Comment by andersenleo** [comment]
@spencergibb Ping? Just checking if there are any 👍 or 👎 feedback on this PR... :)

**Comment by andersenleo** [comment]
(pong?)

**Comment by tommyk-gears** [comment]
@spencergibb do you want me to add some comments explaining the rationale behind some of the changes (not sure if I remember the details, but I could give it a try), or do anything else to assist your review?

**Comment by tommyk-gears** [comment]
We implemented a workaround for this long ago, and there is not much traction on this PR.

**Pull request closed without merging**
