### PR TITLE
Add support for creating composite list of consul tags for spring.cloud.consul.discovery.tags property

### PR DESCRIPTION
**Pull request by aantono**
Proposed implementation for #304

### CODE REVIEW

**Comment by spencergibb** [comment]
Complicated but interesting. That's not a default behavoir for lists like this in all of spring boot/spring cloud. You could have a default tags and combine the two properties that would be much simpler.

**Comment by aantono** [comment]
I've thought about the separate property names route, but had an issue with having to propagate custom configuration to all the applications having to merge the two.  The roll-up composite seemed like a more elegant solution, though I agree that everything else in Spring world for property sources is an override and not a composite.  I could see how there might be a reluctance to break that paradigm, so totally open to other solutions that would solve this use-case without having to make changes to every app's config. :)

**Comment by lowzj** [comment]
I think, It may be simpler that if we add another `Map<String, String>` property `ConsulDiscoveryProperties#externalTags`, and convert it to `List<String>` and merge it into `ConsulDiscoveryProperties#tags`. Then we can add tags as below:

```
spring.cloud.consul.discovery.externalTags.test1=value1
spring.cloud.consul.discovery.externalTags.test2=value2
```

But this is not friendly to adding a non-KeyValue tag.

**Comment by spencergibb** [comment]
We've decided as a team to not go against the default paradigm. Feel free to come up with another solution. Thanks for your time. We really appreciate the community involvement.

**Pull request closed without merging**
