### PR TITLE
Add metadata and enableTagOverride properties for service registration

### PR DESCRIPTION
**Pull request by bradleybarrett**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bradleybarrett Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=578)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=578) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by bradleybarrett** [comment]
Add enhancement mentioned in #575 : Add metadata and enableTagOverride properties for service registration

**Comment by pivotal-issuemaster** [comment]
@bradleybarrett Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=578)!

**Comment by bradleybarrett** [comment]
@spencergibb 
Any advice on replicating [this test failure](https://circleci.com/gh/spring-cloud/spring-cloud-consul/1737#tests/containers/0) from CI? The test case passes on my local machine with `./mvnw clean install`. 

The change reads a map of metadata as a configuration property for ConsulDiscoveryProperties. The test case fails in CI because the metadata map is coming as null. 

Is there anything about the CI environment that would cause problems for  @ConfigurationProperties with a map? Thanks!

**Comment by spencergibb** [comment]
It has to do with the version of consul used by circle 0.7.5

**Comment by spencergibb** [comment]
Blocked by #491

**Comment by spencergibb** [comment]
Closing in favor of #629

**Comment by spencergibb** [comment]
@bradleybarrett I've cherry-picked your change into #629 so you will get attribution and the code mine was based on.

**Pull request closed without merging**
