### PR TITLE
support empty string value (#430)

### PR DESCRIPTION
**Pull request by takeseem**
#430 

if the key exist in consul, convert value=NULL to "".
if you need NULL value, you have to remove the key in consul.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@takeseem Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=431)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=431) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@takeseem Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=431)!

**Comment by takeseem** [comment]
- [INFO] Spring Cloud Consul Sample ......................... FAILURE [ 16.761 s] ???
- it is like javadoc error.
```
[INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:javadoc' has not been previously called for the module: 'org.springframework.cloud:spring-cloud-starter-consul-all:jar:2.0.0.BUILD-SNAPSHOT'. Trying to invoke it...
Picked up _JAVA_OPTIONS: -Xms1024m -Xmx2048m
[WARNING] Creating fake javadoc directory to prevent repeated invocations: /home/ubuntu/spring-cloud-consul/spring-cloud-starter-consul-all/target/apidocs
[ERROR] Error fetching link: /home/ubuntu/spring-cloud-consul/spring-cloud-starter-consul-all/target/apidocs/package-list. Ignored it.
[WARNING] Javadoc Warnings
[WARNING] Picked up _JAVA_OPTIONS: -Xms1024m -Xmx2048m
```

```
[INFO] spring-cloud-consul-dependencies ................... SUCCESS [ 11.654 s]
[INFO] Spring Cloud Consul ................................ SUCCESS [ 29.856 s]
[INFO] Spring Cloud Consul Core ........................... SUCCESS [ 22.360 s]
[INFO] Spring Cloud Consul Config ......................... SUCCESS [01:16 min]
[INFO] Spring Cloud Consul Discovery ...................... SUCCESS [02:57 min]
[INFO] Spring Cloud Consul Binder ......................... SUCCESS [ 15.150 s]
[INFO] Spring Cloud Starter Consul ........................ SUCCESS [  0.104 s]
[INFO] Spring Cloud Starter Consul Bus .................... SUCCESS [  0.108 s]
[INFO] Spring Cloud Starter Consul Config ................. SUCCESS [  0.217 s]
[INFO] Spring Cloud Starter Consul Discovery .............. SUCCESS [  0.156 s]
[INFO] Spring Cloud Starter Consul All .................... SUCCESS [  0.290 s]
[INFO] Spring Cloud Consul Sample ......................... FAILURE [ 16.761 s]
[INFO] Spring Cloud Consul Docs ........................... SKIPPED
```

**Comment by spencergibb** [comment]
If the value of the key returned from the api is null, I don't want to change it.

**Pull request closed without merging**
