### PR TITLE
Add acl token to getCatalogServices call. Fixes gh-440

### PR DESCRIPTION
**Pull request by Spojowa**

### CODE REVIEW

**Comment by spencergibb** [comment]
This is not an obvious fix according to our definition

**Comment by pivotal-issuemaster** [comment]
@Spojowa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=445)!

**Comment by Spojowa** [comment]
@spencergibb Could you take another look at the PR as I have already signed the Contributor License Agreement and changed the type of it so it's no longer "obvious"?

**Comment by rotilho** [comment]
@spencergibb could you merge this PR?

**Comment by rotilho** [comment]
Thanks :)

**Pull request merged**
