### PR TITLE
fix ipv6 formatting for consul API

### PR DESCRIPTION
**Pull request by knalx**
When consul api return IPv6 address - spring cloud consul can't parse it correctly - using it as is.
Added IPv6 address format modification.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@knalx Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=287)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=287) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@knalx Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=287)!

**Comment by knalx** [comment]
Sorry, did not check it. Now it works.

**Comment by spencergibb** [comment]
Squash and merged with some polish via 00697989e3e45be9cc9a65f1d1012f2bf75fa09b

**Pull request closed without merging**
