### PR TITLE
trivial typo fix

### PR DESCRIPTION
**Pull request by FrVaBe**
Obvious Fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@FrVaBe Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=334)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=334) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by FrVaBe** [comment]
Fix is obvious and trivial. No CLA is needed in this case.

**Comment by pivotal-issuemaster** [comment]
@FrVaBe This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by spencergibb** [comment]
@FrVaBe in the future https://cla.pivotal.io/about#submit-obvious-fix

**Comment by FrVaBe** [comment]
Thanks for the obvious-fix hint. Sorry, did not noticed that before.

**Pull request merged**
