### PR TITLE
Added Header support for Service Checks

### PR DESCRIPTION
**Pull request by lomeshpatel**
- Upgraded com.ecwid.consul:consul-api to 1.4.1, which adds
support for Headers in NewService model
- Added new property healthCheckHeaders in ConsulDiscoveryProperties
- Updated docs with instructions on how to set headers

Fixes gh-391

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lomeshpatel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=449)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=449) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@lomeshpatel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=449)!

**Comment by spencergibb** [comment]
Squashed and merged with some polish (notably removing Gson) via fc0c5a74cf4e4c60cf6bbf470f578849727019bd

**Comment by spencergibb** [comment]
Thanks for your first contribution to spring-cloud-consul!

**Comment by lomeshpatel** [comment]
You're very welcome! And Thank you for merging it.

I see that `ToStringCreator` is being used now. Sweet!

**Pull request closed without merging**
