### PR TITLE
Support for Consul datacenters

### PR DESCRIPTION
**Pull request by rkettelerij**
Currently spring-cloud-consul assumes all services in Consul live within the same datacenter. Consul however has support for multiple datacenters and it would be very useful to lookup services using spring-cloud-consul that live in another datacenter.

This PR adds support for multiple datacenters. Since by default the Consul client only looks for services in it's own datacenter is is necessary to specify the datacenter explicitly when querying for a service that lives outside the current datacenter. Therefore I've introduced the `spring.cloud.consul.discovery.server-list-query-datacenters` property. This is a map of serviceIds -> datacenters, in the same way the existing property `spring.cloud.consul.discovery.server-list-query-tags` maps serviceIds to tags. 

This allows one to specify in your spring boot config:
```
endpoint-stores.url=https://stores/api/products
spring.cloud.consul.discovery.server-list-query-datacenters.stores=dc-west
```

I've also added some documentation so users know how to use it. FWIW I'm currently using a patched version of spring-cloud-consul with this PR in our testing environment and everything works properly.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rkettelerij Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=356)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=356) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rkettelerij Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=356)!

**Comment by rkettelerij** [comment]
Note: the failing tests in CircelCI are not related to this issue, master has failing tests.

**Comment by rkettelerij** [comment]
@spencergibb cloud you perhaps have a look at this PR?

**Comment by rkettelerij** [comment]
@spencergibb you mean rename `serverListQueryDatacenters` to `datacenters`?

**Comment by rkettelerij** [comment]
@spencergibb I've updated the PR with your review comment. Renamed `serverListQueryDatacenters` to just `datacenters`

**Comment by spencergibb** [comment]
Squashed and merged with a bit of polish via 6d788d1582c9adc76defd8b8529b767b58d15577

**Pull request closed without merging**
