### PR TITLE
Add support for multiple configuration path prefixes.

### PR DESCRIPTION
**Pull request by colin-mullikin**
This is the most basic implementation to achieve the functionality. A bit more work would need to be done if a different property source order was desired.

Fixes gh-450

### CODE REVIEW

**Comment by spencergibb** [comment]
I'm waiting to merge this based on the waiting for votes label in #450

**Comment by TwinkleTShah** [comment]
Hello @spencergibb,
we also have this requirement. 
when do you plan to merge this PR and make the feature available?

**Comment by kobynet** [comment]
@spencergibb We also are waiting for this change, this is very useful when there are multiple shared context's for multiple services.

**Comment by TwinkleTShah** [comment]
@spencergibb , any plans to get this merged? It would be really helpful if we can merge this.

**Comment by cr-kobyisrael** [comment]
Any updates on this issue?

**Comment by spencergibb** [comment]
Merged with some polish and more tests at 3c4ceb0823ce467c2c8ebc27b1c82c3d14d56331

**Pull request closed without merging**
