### PR TITLE
Add support in ConfigWatch for acl token

### PR DESCRIPTION
**Pull request by dahamr**
Fix for issue #264.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dahamr Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=265)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=265) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by dahamr** [comment]
Forgot to mention that I added a test but can't get any of the tests to succeed on my machine. The consul instance I pulled down based on the travis yml file crashes during the run.

**Comment by spencergibb** [comment]
@dahamr I'm afraid I can't look into this until you've signed the CLA

**Comment by dahamr** [comment]
Sorry. My company have a corporate agreement but for some reason my email domain doesn't work.

**Comment by spencergibb** [comment]
See https://cla.pivotal.io/faq

**Comment by dahamr** [comment]
Done.

**Comment by pivotal-issuemaster** [comment]
@dahamr Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=265)!

**Comment by spencergibb** [comment]
Closed with a test fix via 212d2b9f3d3cf9b947db7a1ddf0347408699b718

**Comment by spencergibb** [comment]
Cherry picked to 1.1.x via d115aee52b35fc235eea038f0f4a6257da65492c

**Comment by spencergibb** [comment]
Cherry picked to master via b78812c66dd706246d8fe8f7c52a220d83848bd7

**Pull request closed without merging**
