### PR TITLE
Fix cast issue when sending an event.

### LINKED ISSUE #458: ConsulSendingHandler assumes payload for message is always a String, but that isn't normally the case
In ConsulSendingHandler.handleMessageInternal, an assumption is made that the payload is of type Message<String> but this is not normally the case. When using spring-cloud-consul-bus, in fact, the default org.springframework.cloud.stream.binding.MessageConverterConfigurer$OutboundContentTypeConvertingInterceptor creates a Message<byte[]>, not a Message<String>, even when the actual content is textual (such as application/json), and this causes a ClassCastException when the ConsulSendingHandler blindly casts the payload to String.

This makes spring-cloud-consul-binder unusable at this time.

### PR DESCRIPTION
**Pull request by plmaheu**
Fixes #458.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@plmaheu Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=641)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=641) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@plmaheu Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=641)!

**Comment by plmaheu** [comment]
@spencergibb Hi, little ping on this. Does it look like an appropriate fix for the issue?

**Comment by dean588** [comment]
Hi ,
I changed my code according to fix. But i still get the error.Any suggestions?

public void handleAlarm(Alarm alarm) {
		ConsulClient consulClient = new ConsulClient();
		Message<String> message = MessageBuilder.withPayload("111111").build();

		Object payload = message.getPayload();
		if (payload instanceof byte[]) {
			payload = Arrays.toString((byte[]) payload);
		}

		EventParams eventParams = new EventParams();
                eventParams.setName("ms-event");
		Response<Event> event = consulClient.eventFire("test", (String) payload, eventParams, QueryParams.DEFAULT);
}

ERROR LOG
[pool-1-thread-1] o.s.c.c.b.ConsulInboundMessageProducer   : Error getting consul events: error occurred in message handler [org.springframework.cloud.consul.binder.ConsulSendingHandler@61141a48]; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.String

**Comment by spencergibb** [comment]
@dean588 your payload is neither a `byte[]` or `String`

**Comment by dean588** [comment]
Could you give me an example how can i generate  a  correct payload for test? I searched  and   tried but couldn't be able to success.
Thanks.

**Pull request closed without merging**
