### PR TITLE
Allow deregister on shutdown to be disabled

### LINKED ISSUE #321: Allow deregister on shutdown to be disabled
We are using [Prometheus](https://prometheus.io/) to automatically monitor spring-boot services as they are started using Consul.  However if a service performs an orderly shutdown it is de-registered from Consul so alerting about it being unavailable is disabled.

I think this can be implemented by introducing a `deregister` property in [ConsulDiscoveryProperties](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryProperties.java#L145) and updating [ConsulAutoServiceRegistration#deregister](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoServiceRegistration.java#L102) to check `!this.properties.isRegister() && !this.properties.isDeregister()`

SO Question [here](https://stackoverflow.com/questions/44647397/how-do-i-configure-spring-cloud-consul-to-not-de-register-on-shutdown)

### PR DESCRIPTION
**Pull request by jonfreedman**
fixes #321

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jonfreedman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=322)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=322) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jonfreedman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=322)!

**Comment by jonfreedman** [comment]
Looks like the tests are fragile as the last commit was just changing comments

**Comment by spencergibb** [comment]
rerunning tests

**Pull request merged**
