### PR TITLE
Fixes #246 - allows for easier extending of the ConsulServerList clas…

### LINKED ISSUE #246: Refactor ConsulServerList for extensibility
The ConsulServerList class is not implemented in a way that allows for clients to extend the class and change it's behavior. My company has some rather unusual requirements about how we interact with Consul so having hooks within this class to change it's default behavior would be great for us. We don't want to make massive changes to how it works, so I would rather not copy/paste/update the existing class.

### PR DESCRIPTION
**Pull request by jjathman**
…s so customization of it's behavior can be done more easily.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jjathman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=247)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=247) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by jjathman** [comment]
I think I've signed the contributor agreement, not sure why it says it's not passing still.

**Comment by pivotal-issuemaster** [comment]
@jjathman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=247)!

**Comment by spencergibb** [comment]
@jjathman needs to be rebased.

**Comment by spencergibb** [comment]
After that, I'll look at merging this week.

**Comment by spencergibb** [comment]
Rebased and merged via 263177a9a63924445f8ad5b8c7a5cbcb3b8123ac

**Pull request closed without merging**
