### PR TITLE
#360 -Added configuration properties for TLSConfig

### PR DESCRIPTION
**Pull request by wdroste**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wdroste Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=400)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=400) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by spencergibb** [comment]
ping @wdroste on signing CLA

**Comment by pivotal-issuemaster** [comment]
@wdroste Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-consul&pullRequestId=400)!

**Comment by berni69** [comment]
@spencergibb  Hi,  seems that @wdroste  had signed the CLA, is there a change to merge his code into spring-cloud-consul ?

**Comment by spencergibb** [comment]
Merged with polish and a test via cc6db701dbd2a92b458977da94467eac3881f85a

**Pull request closed without merging**
